# Generated by Django 5.0.3 on 2024-04-12 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_employee_check_in_remove_employee_check_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="check_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_working_from_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to="app.customuser",
            ),
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
