# Generated by Django 5.0.3 on 2024-04-12 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_employee_check_in_employee_check_out_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_working_from_home",
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in", models.DateTimeField(blank=True, null=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, default=None, null=True)),
                ("is_working_from_home", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="app.employee",
                    ),
                ),
            ],
        ),
    ]
