# Generated by Django 5.0.3 on 2024-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_employee_check_in_employee_check_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="created_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
